name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT
        run: java -jar ./artifacts/app-card-delivery.jar > sut.log 2>&1 &
      - name: Wait for SUT
        run: sleep 10
      - name: Print SUT logs
        run: cat sut.log
      - name: Build with Gradle
        run: ./gradlew test --info
      - name: Kill Java processes
        run: pkill -f 'java'

